package hbn;
// Generated 7 oct. 2013 11:37:48 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Documents generated by hbm2java
 */
public class Documents  implements java.io.Serializable {


     private Integer idDocuments;
     private String nomDocument;
     private String extentionDocument;
     private Long tailleDoc;
     private Set<MetadataDoc> metadataDocs = new HashSet<MetadataDoc>(0);
     private Set<Folders> folderses = new HashSet<Folders>(0);

    public Documents() {
    }

    public Documents(String nomDocument, String extentionDocument, Long tailleDoc, Set<MetadataDoc> metadataDocs, Set<Folders> folderses) {
       this.nomDocument = nomDocument;
       this.extentionDocument = extentionDocument;
       this.tailleDoc = tailleDoc;
       this.metadataDocs = metadataDocs;
       this.folderses = folderses;
    }
   
    public Integer getIdDocuments() {
        return this.idDocuments;
    }
    
    public void setIdDocuments(Integer idDocuments) {
        this.idDocuments = idDocuments;
    }
    public String getNomDocument() {
        return this.nomDocument;
    }
    
    public void setNomDocument(String nomDocument) {
        this.nomDocument = nomDocument;
    }
    public String getExtentionDocument() {
        return this.extentionDocument;
    }
    
    public void setExtentionDocument(String extentionDocument) {
        this.extentionDocument = extentionDocument;
    }
    public Long getTailleDoc() {
        return this.tailleDoc;
    }
    
    public void setTailleDoc(Long tailleDoc) {
        this.tailleDoc = tailleDoc;
    }
    public Set<MetadataDoc> getMetadataDocs() {
        return this.metadataDocs;
    }
    
    public void setMetadataDocs(Set<MetadataDoc> metadataDocs) {
        this.metadataDocs = metadataDocs;
    }
    public Set<Folders> getFolderses() {
        return this.folderses;
    }
    
    public void setFolderses(Set<Folders> folderses) {
        this.folderses = folderses;
    }




}


