package hbn;
// Generated 7 oct. 2013 11:37:48 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Folders generated by hbm2java
 */
public class Folders  implements java.io.Serializable {


     private Integer idFolder;
     private String intituleFolder;
     private String typeFolder;
     private String cheminFolder;
     private Long tailleFolder;
     private Set<Documents> documentses = new HashSet<Documents>(0);
     private Set<MetadataFold> metadataFolds = new HashSet<MetadataFold>(0);

    public Folders() {
    }

    public Folders(String intituleFolder, String typeFolder, String cheminFolder, Long tailleFolder, Set<Documents> documentses, Set<MetadataFold> metadataFolds) {
       this.intituleFolder = intituleFolder;
       this.typeFolder = typeFolder;
       this.cheminFolder = cheminFolder;
       this.tailleFolder = tailleFolder;
       this.documentses = documentses;
       this.metadataFolds = metadataFolds;
    }
   
    public Integer getIdFolder() {
        return this.idFolder;
    }
    
    public void setIdFolder(Integer idFolder) {
        this.idFolder = idFolder;
    }
    public String getIntituleFolder() {
        return this.intituleFolder;
    }
    
    public void setIntituleFolder(String intituleFolder) {
        this.intituleFolder = intituleFolder;
    }
    public String getTypeFolder() {
        return this.typeFolder;
    }
    
    public void setTypeFolder(String typeFolder) {
        this.typeFolder = typeFolder;
    }
    public String getCheminFolder() {
        return this.cheminFolder;
    }
    
    public void setCheminFolder(String cheminFolder) {
        this.cheminFolder = cheminFolder;
    }
    public Long getTailleFolder() {
        return this.tailleFolder;
    }
    
    public void setTailleFolder(Long tailleFolder) {
        this.tailleFolder = tailleFolder;
    }
    public Set<Documents> getDocumentses() {
        return this.documentses;
    }
    
    public void setDocumentses(Set<Documents> documentses) {
        this.documentses = documentses;
    }
    public Set<MetadataFold> getMetadataFolds() {
        return this.metadataFolds;
    }
    
    public void setMetadataFolds(Set<MetadataFold> metadataFolds) {
        this.metadataFolds = metadataFolds;
    }




}


