package hbn;
// Generated 7 oct. 2013 11:37:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MetadataDoc generated by hbm2java
 */
public class MetadataDoc  implements java.io.Serializable {


     private MetadataDocId id;
     private Metatype metatype;
     private Documents documents;
     private String valeurDoc;
     private Date dateDoc;

    public MetadataDoc() {
    }

	
    public MetadataDoc(MetadataDocId id, Metatype metatype, Documents documents) {
        this.id = id;
        this.metatype = metatype;
        this.documents = documents;
    }
    public MetadataDoc(MetadataDocId id, Metatype metatype, Documents documents, String valeurDoc, Date dateDoc) {
       this.id = id;
       this.metatype = metatype;
       this.documents = documents;
       this.valeurDoc = valeurDoc;
       this.dateDoc = dateDoc;
    }
   
    public MetadataDocId getId() {
        return this.id;
    }
    
    public void setId(MetadataDocId id) {
        this.id = id;
    }
    public Metatype getMetatype() {
        return this.metatype;
    }
    
    public void setMetatype(Metatype metatype) {
        this.metatype = metatype;
    }
    public Documents getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Documents documents) {
        this.documents = documents;
    }
    public String getValeurDoc() {
        return this.valeurDoc;
    }
    
    public void setValeurDoc(String valeurDoc) {
        this.valeurDoc = valeurDoc;
    }
    public Date getDateDoc() {
        return this.dateDoc;
    }
    
    public void setDateDoc(Date dateDoc) {
        this.dateDoc = dateDoc;
    }




}


