package hbn;
// Generated 7 oct. 2013 11:37:48 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MetadataFold generated by hbm2java
 */
public class MetadataFold  implements java.io.Serializable {


     private MetadataFoldId id;
     private Metatype metatype;
     private Folders folders;
     private String valeurFold;
     private Date dateFold;

    public MetadataFold() {
    }

	
    public MetadataFold(MetadataFoldId id, Metatype metatype, Folders folders) {
        this.id = id;
        this.metatype = metatype;
        this.folders = folders;
    }
    public MetadataFold(MetadataFoldId id, Metatype metatype, Folders folders, String valeurFold, Date dateFold) {
       this.id = id;
       this.metatype = metatype;
       this.folders = folders;
       this.valeurFold = valeurFold;
       this.dateFold = dateFold;
    }
   
    public MetadataFoldId getId() {
        return this.id;
    }
    
    public void setId(MetadataFoldId id) {
        this.id = id;
    }
    public Metatype getMetatype() {
        return this.metatype;
    }
    
    public void setMetatype(Metatype metatype) {
        this.metatype = metatype;
    }
    public Folders getFolders() {
        return this.folders;
    }
    
    public void setFolders(Folders folders) {
        this.folders = folders;
    }
    public String getValeurFold() {
        return this.valeurFold;
    }
    
    public void setValeurFold(String valeurFold) {
        this.valeurFold = valeurFold;
    }
    public Date getDateFold() {
        return this.dateFold;
    }
    
    public void setDateFold(Date dateFold) {
        this.dateFold = dateFold;
    }




}


