package hbn;
// Generated 7 oct. 2013 11:37:48 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Metatype generated by hbm2java
 */
public class Metatype  implements java.io.Serializable {


     private Integer idMetadata;
     private String intituleMetadata;
     private Set<MetadataFold> metadataFolds = new HashSet<MetadataFold>(0);
     private Set<MetadataDoc> metadataDocs = new HashSet<MetadataDoc>(0);

    public Metatype() {
    }

    public Metatype(String intituleMetadata, Set<MetadataFold> metadataFolds, Set<MetadataDoc> metadataDocs) {
       this.intituleMetadata = intituleMetadata;
       this.metadataFolds = metadataFolds;
       this.metadataDocs = metadataDocs;
    }
   
    public Integer getIdMetadata() {
        return this.idMetadata;
    }
    
    public void setIdMetadata(Integer idMetadata) {
        this.idMetadata = idMetadata;
    }
    public String getIntituleMetadata() {
        return this.intituleMetadata;
    }
    
    public void setIntituleMetadata(String intituleMetadata) {
        this.intituleMetadata = intituleMetadata;
    }
    public Set<MetadataFold> getMetadataFolds() {
        return this.metadataFolds;
    }
    
    public void setMetadataFolds(Set<MetadataFold> metadataFolds) {
        this.metadataFolds = metadataFolds;
    }
    public Set<MetadataDoc> getMetadataDocs() {
        return this.metadataDocs;
    }
    
    public void setMetadataDocs(Set<MetadataDoc> metadataDocs) {
        this.metadataDocs = metadataDocs;
    }




}


