package hbn;
// Generated 7 oct. 2013 11:37:48 by Hibernate Tools 3.2.1.GA



/**
 * MetadataDocId generated by hbm2java
 */
public class MetadataDocId  implements java.io.Serializable {


     private int idDocuments;
     private int idMetadata;

    public MetadataDocId() {
    }

    public MetadataDocId(int idDocuments, int idMetadata) {
       this.idDocuments = idDocuments;
       this.idMetadata = idMetadata;
    }
   
    public int getIdDocuments() {
        return this.idDocuments;
    }
    
    public void setIdDocuments(int idDocuments) {
        this.idDocuments = idDocuments;
    }
    public int getIdMetadata() {
        return this.idMetadata;
    }
    
    public void setIdMetadata(int idMetadata) {
        this.idMetadata = idMetadata;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MetadataDocId) ) return false;
		 MetadataDocId castOther = ( MetadataDocId ) other; 
         
		 return (this.getIdDocuments()==castOther.getIdDocuments())
 && (this.getIdMetadata()==castOther.getIdMetadata());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDocuments();
         result = 37 * result + this.getIdMetadata();
         return result;
   }   


}


